baseURL: "https://poly-blogs.com/"
title: Poly Blogs
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-R02YEESHEW

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Poly Blogs
  keywords: [Blog, Science]
  author: Gautier Maréchal
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
params:
    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "/favicons/favicon-16x16.png"
        favicon32x32: "/favicons/favicon-32x32.png"
        apple_touch_icon: "/favicons/apple-touch-icon.png"
        safari_pinned_tab: "/favicons/safari-pinned-tab.svg"
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink"]
defaultContentLanguage: fr
languages:
  en:
    languageName: "English"
    languageAltTitle: English
    weight: 10
    DateFormat: "2 January 2006"
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    homeInfoParams:
      Title: Poly Blogs
      Content: |+
        For years with my friend Hugo, we have been telling ourselves that there is a problem with our friends: they would like to learn more but cannot take the step of reading and documenting themselves. With the amount of resources everywhere on all the subjects of the world, they get lost and we understand...

        Everyone is curious but when it comes to doing, it's more complicated.

        Well, that's why we created this platform called Poly: a place where we try to popularize interesting scientific and philosophical subjects, and talk about the books we've read.

        A clear place, where you don't search for hours for what you want to learn. We just arrive and we like it.

        BASICALLY: Poly is a science, philosophy, and book blog.

        For now, this blog is intended for our circles of friends, but why not make it something global?

        Our contacts:
          Gautier Maréchal: gautier.marechal@gaut[dot]io
          Hugo Soubrier:
    menu:
      main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 20
        - identifier: search
          name: Search
          url: search/
          weight: 30
        - identifier: books-graph
          name: Books Graph
          url: /books-graph/
          weight: 40

  fr:
    languageName: "French"
    languageAltTitle: Français
    weight: 10
    DateFormat: "2 January 2006"
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    homeInfoParams:
      Title: Poly Blogs
      Content: |+
        Depuis des années avec mon ami Hugo, nous nous disons qu'il y'a un problème chez nos amis: ils aimeraient apprendre davantage mais n'arrivent pas à franchir le pas de lire et de se documenter. Avec la quantité de ressources partout sur tous les sujets du monde, ils se perdent et on comprend bien...

        Tout le monde est curieux mais quand il s'agit de faire, c'est plus compliqué.

        Et bien voilà pourquoi on a crée cette plateforme baptisée Poly: un endroit où nous tentons de vulgariser des sujets scientifiques et philosophiques intéressants, et de parler des livres qu'on a lu.

        Un endroit clair, où on cherche pas pendant des heures ce qu'on veut apprendre. Juste on débarque et on kiffe.

        EN GROS: Poly est un blog de science, de philosophie et de livres.

        Pour l'instant, ce blog est destiné à nos cercles d'amis, mais pourquoi pas en faire quelque chose de global?

        Nos contacts: 
          Gautier Maréchal: gautier.marechal@gaut[dot]io 
          Hugo Soubrier:

    menu:
      main:
        - identifier: categories
          name: Catégories
          url: /categories/
          weight: 10
        - identifier: posts
          name: Publications
          url: /posts/
          weight: 20
        - identifier: search
          name: Rechercher
          url: search/
          weight: 30
        - identifier: books-graph
          name: Graphe de Livres
          url: /books-graph/
          weight: 40
