baseURL: "https://poly-blogs.com/"
title: Poly Blogs
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-R02YEESHEW

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Poly Blogs
  keywords: [Blog, Science]
  author: Gautier Maréchal
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
params:
    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "/favicons/favicon-16x16.png"
        favicon32x32: "/favicons/favicon-32x32.png"
        apple_touch_icon: "/favicons/apple-touch-icon.png"
        safari_pinned_tab: "/favicons/safari-pinned-tab.svg"
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink"]
defaultContentLanguage: fr
languages:
  en:
    languageName: "English"
    languageAltTitle: English
    weight: 10
    DateFormat: "2 January 2006"
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    homeInfoParams:
      Title: Poly Blogs
      Content: |+
        Poly is a blog about multiple subjects in various disciplines such as science, history or philosophy. The ultimate goal is to arouse the curiosity of its readers.

        This blog aspires to be generalist. With each publication, a subject is treated in an introductory way, without remaining too superficial.

        The idea is to get the first technical aspects of the subject, so that the reader understands, without the post being illegible and boring.

        This blog has no claim to become a serious scientific journal.

        It exists for the sole purpose of providing interesting content for readers with a thirst for learning. The idea is to provide valuable information in this ocean of noise that engulfs us on the internet.
    menu:
      main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: search
          name: Search
          url: search/
          weight: 20

  fr:
    languageName: "French"
    languageAltTitle: Français
    weight: 10
    DateFormat: "2 January 2006"
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    homeInfoParams:
      Title: Poly Blogs
      Content: |+
        Poly est un blog de sur de multiples sujets dans diverses discipline comme la science, l’histoire ou la philosophie. 
        
        L’ultime but est de susciter la curiosité de ses lecteurs.
        

        Ce blog aspire à être généraliste. À chaque publication, un sujet est traité de manière introductive, sans rester trop en surface.


        L’idée est d’aller chercher les premiers aspects techniques du sujet, pour que le lecteur comprenne, sans que le billet soit illisible et barbant.


        Ce blog n’a aucune prétention de devenir une revue scientifique sérieuse.


        Il existe dans l’unique but d’apporter un contenu intéressant pour des lecteurs possédant une soif d’apprendre. L’idée est de donner une information de valeur dans cet océan de bruit qui nous englouti sur internet.
    menu:
      main:
        - identifier: categories
          name: Catégories
          url: /categories/
          weight: 10
        - identifier: search
          name: Rechercher
          url: search/
          weight: 20
